name: build-db

on:
  push:
    branches:
      - main
      - cache
    paths:
      - .github/workflows/*.yml
      - Database/**/*.swift

jobs:
  build-db:
    name: build-db

    runs-on: macos-14  # M1

    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
          path: |
            Database/.build
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build Database
        run: xcrun --sdk macosx swift run -c release --package-path Database DatabaseBuilder "test"

