name: build-db

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*.yml
      - Database/**/*.swift

jobs:
  build-db:
    name: build-db

    strategy:
      matrix:
        os:
          - macos-13  # Intel
          - macos-14  # M1
    runs-on: ${{ matrix.os }}

    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app

    steps:
      - name: Check Architecture
        id: arch
        run: echo "arch=$(uname -m)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
          path: |
            Database/.build
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-${{ runner.arch }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-spm-

      - name: Build Database
        run: xcrun --sdk macosx swift run -c release --package-path Database DatabaseBuilder ${{ steps.arch.outputs.arch }}

      - name: Upload Database
        uses: actions/upload-artifact@v4
        with:
          name: sample-realm-${{ steps.arch.outputs.arch }}
          path: sample-*.realm
