name: build-db

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*.yml
      - Database/**/*.swift

jobs:
  build-db:
    name: build-db

    strategy:
      matrix:
        os:
          - macos-13  # Intel
          - macos-14  # M1
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check Architecture
        id: arch
        run: echo "arch=$(uname -m)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Swift Package Manager
        uses: actions/cache@v2
        with:
          path: Database/.build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"

      - name: Build Database
        run: xcrun --sdk macosx swift run -c release --package-path Database DatabaseBuilder

      - name: Upload Database
        uses: actions/upload-artifact@v4
        with:
          name: sample-realm-${{ steps.arch.outputs.arch }}
          path: sample-*.realm
